### ISSUE TITLE
Having hard time to understand webpack.DefinePlugin on going to production step

### ISSUE THREAD

**Issue by sakhmedbayev** [mbrochh/django-reactjs-boilerplate#16]
Hi @mbrochh 

Thanks a lot for this outstanding tutorial. I am following it closely :+1: 

Can you please elaborate on these settings which you provided in the "Going to Production" step?
```
new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify('staging'),
      'BASE_API_URL': JSON.stringify('https://sandbox.example.com/api/v1/'),
  }}),
```

What does `BASE_API_URL` represents? Some API endpoint on your django server side?

**Comment by fohrloop** [comment]
Hi @sakhmedbayev 

I was searching for an answer to the same thing. I think it is only used in one component (reactjs/components/SampleAppContainer.jsx)

>             <Headline>Sample App!</Headline>
>             <div style={[styles.button]} onClick={() => this.handleClick()}>INCREASE</div>
>             <p style={[styles.counter]}>{counters.clicks}</p>
>             <p>{process.env.BASE_API_URL}</p>

and thus it is just a "self made variable" for a API endpoint. I assume that the main reason is that is you use the same API base url in many places, you can still easily update the url from the config. The name of the variable could be anything you like.

See also: [https://nodejs.org/api/process.html#process_process_env](https://nodejs.org/api/process.html#process_process_env)

**Comment by mbrochh** [comment]
Sorry for the late reply. Glad that you basically found the answer to your question on your own ;)

Yes, `BASE_API_URL` is supposed to point to your Django backend.
