### ISSUE TITLE
Hot-reloading not working with chrome 

### ISSUE THREAD

**Issue by mdansei** [mbrochh/django-reactjs-boilerplate#18]
I get this error in chrome console when I save my changes and webpack compiles : 

`XMLHttpRequest cannot load http://localhost:3000/assets/bundles/70e617bfdfcfc79ab38b.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access.`

I tried using django-cors-headers library, but it didn't work !

Could somebody help me ?

**Comment by mdansei** [comment]
#13 solved mine

**Comment by acidSnakej** [comment]
Thank you!
