### ISSUE TITLE
Python 3 - Missing parentheses in call to 'print' in settings.py

### ISSUE THREAD

**Issue by dkaufhold** [mbrochh/django-reactjs-boilerplate#4]
The `print` command here https://github.com/mbrochh/django-reactjs-boilerplate/blob/master/django/djreact/settings.py#L126 requires parentheses when using python 3

**Comment by mbrochh** [comment]
fixed in https://github.com/mbrochh/django-reactjs-boilerplate/commit/e16a8aefa00baff9e6951df09cef4e70c26b0d3b
