### ISSUE TITLE
there is something after the url that can't understand

### ISSUE THREAD

**Issue by markrui3** [mbrochh/django-reactjs-boilerplate#6]
when I set up all the things and type url in chrome, such as: http://localhost:8000 and my url turn to http://localhost:8000/?_k=i26vli. The _k is always changing while refresh. 
How does it come?
Thank you for replying me.

**Comment by mbrochh** [comment]
Hmm... I don't think I ever saw that part... are you sure you followed the instructions closely? At what part do you get that URL?

**Comment by markrui3** [comment]
Sorry, the project did not generate the result. Maybe it is because of my using react-router. 
Thanks for your reply.
